### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by rabbit2rabbit** [yinghualuowu/GenshinDailyHelper#2]
Run dotnet run -p ./GenshinDailyHelper ${Cookie}
[07:02:29]:开始签到
[07:02:30]:开始签到 账号1
[07:02:34]:请求接口时出现异常请求异常登录失效，请重新登录
Unhandled exception. GenshinDailyHelper.Exception.GenShinException: 请求异常登录失效，请重新登录
   at GenshinDailyHelper.Entities.RootEntity`1.CheckOutCodeAndSleep() in /home/runner/work/GenshinDailyHelper/GenshinDailyHelper/GenshinDailyHelper/Entities/RootEntity.cs:line 44
   at GenshinDailyHelper.Program.Main(String[] args) in /home/runner/work/GenshinDailyHelper/GenshinDailyHelper/GenshinDailyHelper/Program.cs:line 45
   at GenshinDailyHelper.Program.<Main>(String[] args)
Error: Process completed with exit code 134.

**Comment by yinghualuowu** [comment]
cookie设置的不对。
如果有设置过cookie还是无法签到，请重新在论坛登陆后再次按照操作步骤设置cookie。
ps:建议用谷歌浏览器，出现f12进入断点的情况，可以百度如果取消断点。

**Comment by rabbit2rabbit** [comment]
new sceret的name没要求吧？

**Comment by rabbit2rabbit** [comment]
value值是__MHYUUID=;    UM_distinctid=;    __ga=;ltoken=;    ltuid=;    CNZZDATA1275023096=;    gid=;    _gat=;  这些是吗？前面要带上“cookie:”吗？

**Comment by yinghualuowu** [comment]
> value值是__MHYUUID=; UM_distinctid=; __ga=;ltoken=; ltuid=; CNZZDATA1275023096=; gid=; _gat=; 这些是吗？前面要带上“cookie:”吗？

我看了你的执行报错，应该是cookie值不对，这种重新登录拉取最新的cookies就能成功执行了。
value是不用带```cookie:```的。

**Comment by yinghualuowu** [comment]
目前跟进到 项目已经可以运行了，关闭该issue
